### ISSUE TITLE
Issue while importing SDK as module.

### ISSUE THREAD

**Issue by akkishinde** [freshdesk/hotline-android#1]
Hi, 
When we import SDK as module in app then following error occurs,

`Error:Plugin with id 'com.github.dcendents.android-maven' not found.`

Though, I found a workaround for this,

We have to add 
compile `com.github.vajro:MaterialDesignLibrary:1.6` as a dependancy 
and have to remove `apply plugin: 'com.github.dcendents.android-maven'`

and add this in Gradle,

```
repositories {
        maven { url "https://jitpack.io" }
    }
```

**Comment by hrishikesh-p** [comment]
@akkishinde Akshay , Thanks for the notes on the fix. 

You do need to add the jitpack repository to your build.gradle. This is required since we host the SDK out of jitpack Maven repository. 

The other error is not related to the hotline SDK. Vajro - Material Design Library is not a dependency for HotlineSDK. [ref](http://www.methodscount.com/?lib=com.github.freshdesk%3Ahotline-android%3A1.%2B)
