### ISSUE TITLE
How to force user to input username/email?

### ISSUE THREAD

**Issue by riyaz** [freshdesk/hotline-android#13]
This was available in freshdesk mobihelp SDK.

```
    config.setFeedbackType(FeedbackType.NAME_AND_EMAIL_REQUIRED);

```

**Comment by tryprasannan** [comment]
@riyaz Unfortunately this is not supported out of the box with Hotline SDK at this point. This needs to be captured from within the app (may require building the UI, if your app don't already have any UI to capture this) and passed to Hotline. However we'll soon share a snippet/sample to make this easier.

**Comment by hrishikesh-p** [comment]
@riyaz  If your app already has a user login, you may use `Hotline.updateUser` API to update the user's name , email or phone number.  you can update this at any time. You can also pass in an external identifier which can be used to identify the user in your system. 

We have a [feature  called smart plugs](https://support.hotline.io/support/solutions/articles/221171-what-are-smart-plugs-) that allow you to pull information from your system and view it within hotline using the external id.  

If your app doesn't already have user information, I am afraid you will have do what @tryprasannan  has recommended i.e build your own UI/Form to collect user information. 

Closing this issue here. Please reach us out at support@hotline.io if you need further assistance.
