### ISSUE TITLE
Support for Vector Drawables as icons

### ISSUE THREAD

**Issue by okmanideep** [freshdesk/hotline-android#4]
From [Android Support Library 23.2](http://android-developers.blogspot.in/2016/02/android-support-library-232.html), we can use `VectorDrawable`s in android apps which support Android versions lower than `LOLLIPOP`. **They reduce a tremendous amount of space** in the final app.

**Comment by tryprasannan** [comment]
@manidesto Sorry we haven't gotten to this.  

We like to keep the SDK flexible, in this case in terms of Android version targeted, there are apps out there built with versions of Android earlier than Marshmallow (5.0, 5.1 etc) and since `VectorDrawables` is supported only from a specific version of the appcompat (23.2 as you have pointed out, which also requires building the app with Marshmallow) over which the Hotline SDK has no control. We don't want to force apps to be built with specific versions of Android or specific versions of appcompat just to use the Hotline SDK as much as possible.

And the size of image resources (that can be replaced by vector drawables) of the SDK at this point is too small to make a big impact (its about 5 % in terms of the size of the SDK). So we aren't taking up this at this point. We'll reevaluate this at a later point.
