### ISSUE TITLE
Hotline Service running in the background

### ISSUE THREAD

**Issue by iangmaia** [freshdesk/hotline-android#7]
I've noticed some service from Hotline running in the background. A few questions:
1) What is that for? Perhaps for polling of new messages when Push isn't enabled?
2) Is there any way of disabling it? 
3) It spits out some logging, perhaps that could be configured as well?
08-15 15:31:22.189 2971-3287/<app>I/HOTLINE_SERVICE: Now Processing h
08-15 15:31:22.204 2971-3287/<app>I/HOTLINE_SERVICE: Now Processing h
08-15 15:31:22.213 2971-3287/<app>I/HOTLINE_SERVICE: Now Processing h
08-15 15:31:22.220 2971-3287/<app>I/HOTLINE_SERVICE: Now Processing h
08-15 15:31:22.222 2971-3287/<app>I/HOTLINE_SERVICE: Now Processing k
08-15 15:31:22.224 2971-3287/<app>I/HOTLINE_SERVICE: Now Processing k
08-15 15:31:22.224 2971-3287/<app>I/HOTLINE_SERVICE: Now Processing k
08-15 15:31:22.226 2971-3287/<app>I/HOTLINE_SERVICE: Now Processing k

**Comment by hrishikesh-p** [comment]
@iangmaia We use an IntentService for all Hotline related processing. It only runs when there is something to process. Most common of these  is when unreadcount of notifications is requested. 

We would like to retain this log since this gives us an idea of the events the SDK is processing and helps debugging.
